### PR TITLE
Replaced 'char' variable name because is a reserved word.

### PR DESCRIPTION
**Pull request by ZxBud**
For more informations about reserved word see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

### CODE REVIEW

**Comment by mdevils** [comment]
Hello @ZxBud, how does it disturb you?

**Comment by ZxBud** [comment]
Hello @mdevils, some linter fails

**Comment by ZxBud** [comment]
Up!

**Comment by mdevils** [comment]
Hello! Sorry for a delay. Thank you for your contribution!

**Comment by ZxBud** [comment]
Thankyou for the merge ;)

**Pull request merged**
