### PR TITLE
Fix #15 - Change order of the entities

### LINKED ISSUE #15: Single and double CloseCurlyQuote entities aren’t properly encoded
The problem is with `’` (i.e. `&rsquo;`) and `”` (i.e. `&rdquo;`), which are encoded as `&CloseCurlyQuote;` and `&CloseCurlyDoubleQuote;`, respectively.

See this [test case](https://tonicdev.com/acusti/html-entities-test-case-close-curly-quote)

**UPDATE:** It seems that the issue is specific to the `Html5Entities` class. When I repeated the test using `require('html-entities').Html4Entities`, the encoding worked (see updated test case above).

### PR DESCRIPTION
**Pull request by Kiwka**
Move the CloseCurlyQuote and CloseCurlyDoubleQuote to be after rsquo and rdquo, so for encoding will be used right pair of the entities rsquo - lsquo and rdquo - ldquo, and it will keep possibility to decode entities CloseCurlyQuote and CloseCurlyDoubleQuote
- adding checks does the passed string exists - to prevent error form trying to obtain property length of undefined

### CODE REVIEW

**Comment by mdevils** [comment]
Hello @Kiwka,

Thank you very much for contributing.

Can you please provide some examples before/after. It's hard to understand the change otherwise.

**Comment by Kiwka** [comment]
Hi @mdevils 

This is the fix for the opened issue https://github.com/mdevils/node-html-entities/issues/15 in this project. The description includes use case of the wrong behavior. 

Example: entities.encode('‘Single opening curly quotes’ seem just fine');
Before fix: "&lsquo;Single opening curly quotes&CloseCurlyQuote; seem just fine"
After fix: "&lsquo;Single opening curly quotes&rsquo; seem just fine"

**Comment by mdevils** [comment]
Thank you for your contribution.

**Comment by mdevils** [comment]
Published in version `1.2.1`.

**Pull request merged**
